name: YouTube Daily Updater

on:
  schedule:
    - cron: '15 10 * * *'  # щодня о 10:15 UTC (13:15 за Києвом)
  workflow_dispatch:


jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v3

      - name: Встановити Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановити залежності
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client pytz requests

      - name: Створити credentials файл
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > google-credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Запустити скрипт
        run: |
          python3 main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
